apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# metallb
- ../../metallb/overlays/prod

# ingress-nginx
- ../../ingress-nginx/overlays/prod

# external-secrets
- ../../external-secrets/overlays/prod

# onepassword
- ../../1password/overlays/prod

# cert-manager
- ../../cert-manager/overlays/prod

# reloader
- ../../reloader/overlays/prod

# personal-profile
- ../../personal-profile/overlays/prod
- ../../personal-profile/overlays/dev

# adguard
- ../../adguard/overlays/prod-a
- ../../adguard/overlays/prod-b