apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
# onepassword
- ../../1password/overlays/vdgt-k3s

# external-secrets
- ../../external-secrets/overlays/vdgt-k3s

# stackweaver
- ../../stackweaver/overlays/vdgt-k3s
