apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Application
  patch: |-
    - op: replace
      path: /metadata/name
      value: root-app
    - op: replace
      path: /metadata/labels/env
      value: production
    - op: replace
      path: /spec/source/targetRevision
      value: main
    - op: replace
      path: /spec/source/path
      value: argocd-apps/manifests/overlays/prod
