apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: TO_OVERLAY
  namespace: argocd
  labels:
    env: TO_OVERLAY
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/jterpstra1/argocd-apps.git
    targetRevision: TO_OVERLAY
    path: TO_OVERLAY
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - PruneLast=true
